let sb=null;
const cfg=window.FARTAKA_SUPABASE_CONFIG||{};
// V10: refresh locally cached logo assets on every deployment
const ASSET_VERSION='20260830-v11';
function refreshBrandAssets(){document.querySelectorAll('img[src^="logo.svg"]').forEach(img=>{const base=img.src.split('?')[0];img.src=base+'?v='+ASSET_VERSION})}

if(window.supabase&&cfg.supabase_url&&cfg.supabase_publishable_key){sb=window.supabase.createClient(cfg.supabase_url,cfg.supabase_publishable_key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=n=>Number(n||0).toLocaleString('ar-EG',{maximumFractionDigits:2});
let products=[],currentUser=null,isAdmin=false,cart=JSON.parse(localStorage.getItem('fartaka_cart')||'[]'),favorites=new Set(JSON.parse(localStorage.getItem('fartaka_favorites')||'[]')),activeCat='الكل',registerMode=false,siteSettings={};
const cats=['الكل','إلكترونيات','منزل','أزياء','أطفال','رياضة','جمال','مستلزمات'];
const defaultCatImages=['assets/categories/electronics.svg','assets/categories/home.svg','assets/categories/fashion.svg','assets/categories/kids.svg','assets/categories/sports.svg','assets/categories/beauty.svg','assets/categories/supplies.svg'];
function toast(t,kind=''){const x=$('toast');x.textContent=t;x.className='toast show '+kind;clearTimeout(window._t);window._t=setTimeout(()=>x.className='toast',3200)}
function openModal(id){const x=$(id);if(!x)return;x.hidden=false;x.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}
function closeModal(id){const x=$(id);if(!x)return;x.hidden=true;x.setAttribute('aria-hidden','true');if(!document.querySelector('.modal:not([hidden])'))document.body.classList.remove('modal-open')}
function saveLocal(){localStorage.setItem('fartaka_cart',JSON.stringify(cart));localStorage.setItem('fartaka_favorites',JSON.stringify([...favorites]))}
function safeUrl(v){try{let u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
function setAuthStatus(t,ok=false){const x=$('authStatus');if(x){x.textContent=t;x.className='authStatus '+(ok?'ok':'')}}
async function init(){
  $('categoryGrid').innerHTML=cats.slice(1).map((c,i)=>{const im=(siteSettings.category_images||[])[i]||defaultCatImages[i];return `<button onclick="filterCat('${esc(c)}')">${im?`<img class="catImg" src="${esc(im)}" alt="${esc(c)}">`:`<span class="catFallback">${{'إلكترونيات':'📱','منزل':'🏠','أزياء':'👕','أطفال':'🧸','رياضة':'⚽','جمال':'💄','مستلزمات':'🧰'}[c]}</span>`}<b>${esc(c)}</b></button>`}).join('');
  $('catChips').innerHTML=cats.map(c=>`<button class="chip ${c==='الكل'?'active':''}" onclick="filterCat('${esc(c)}')">${esc(c)}</button>`).join('');
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelectorAll('.modal:not([hidden])').forEach(m=>closeModal(m.id));closeMenu()}});
  document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));
  document.querySelectorAll('.close').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();closeModal(b.closest('.modal')?.id)}));
  if(sb){const {data,error}=await sb.auth.getSession();if(error)toast('تعذر قراءة جلسة الحساب','error');if(data.session)await setUser(data.session.user);sb.auth.onAuthStateChange(async(_e,s)=>{await setUser(s?.user||null)})} else toast('الموقع غير مربوط بـ Supabase بعد','error');
  await loadSite();refreshBrandAssets();await loadProducts();updateCart();renderAccount();diagnose();
}
async function diagnose(){const box=$('connectionStatus');if(!box)return;if(!sb){box.textContent='غير متصل';return}try{const {error}=await sb.from('products').select('id').limit(1);box.textContent=error?'اتصال قاعدة البيانات يحتاج إعداد':'متصل بـ Supabase ✓';box.className=error?'bad':'good'}catch{box.textContent='تعذر الاتصال';box.className='bad'}}
async function setUser(user){currentUser=user||null;isAdmin=false;if(user&&sb){const {data}=await sb.from('profiles').select('full_name,phone,address,city,role').eq('id',user.id).maybeSingle();isAdmin=data?.role==='admin';if(data)currentUser.profile=data}renderAccount();if(isAdmin)renderAdmin();}
async function loadSite(){if(!sb)return;const {data}=await sb.from('site_settings').select('*').limit(1).maybeSingle();if(data){siteSettings=data;$('heroTitle').textContent=data.hero_title||'تسوق أذكى. اختيارات أكثر.';$('heroText').textContent=data.hero_text||'منتجات وعروض وروابط أفليت وطلبات في تجربة واحدة.';if(data.hero_image)$('hero').style.backgroundImage=`linear-gradient(90deg,#11101af0,#11101aa8),url("${esc(data.hero_image)}")`;if(data.logo_image){const bust=(data.updated_at?new Date(data.updated_at).getTime():Date.now());document.querySelectorAll('.logo img,.sideTitle img,#footerLogo').forEach(x=>{x.src=data.logo_image+(data.logo_image.includes('?')?'&':'?')+'v='+bust})}if(data.footer_text)$('footerText').textContent=data.footer_text;renderCategoryImages()}}
function renderCategoryImages(){const imgs=siteSettings.category_images||[];document.querySelectorAll('#categoryGrid button').forEach((b,i)=>{const im=imgs[i]||defaultCatImages[i];if(im){const old=b.querySelector('.catFallback');if(old)old.outerHTML=`<img class="catImg" src="${esc(im)}" alt="${esc(cats[i+1])}">`;else if(!b.querySelector('.catImg'))b.insertAdjacentHTML('afterbegin',`<img class="catImg" src="${esc(im)}" alt="${esc(cats[i+1])}">`)}})}
async function loadProducts(){if(!sb)return;const {data,error}=await sb.from('products').select('*').order('created_at',{ascending:false});if(error){console.error(error);toast('قاعدة البيانات لا تسمح بتحميل المنتجات: '+error.message,'error');return}products=(data||[]).map(p=>({id:p.id,name:p.name,price:+p.price||0,old:+(p.old_price||p.price)||0,cat:p.category||'عام',store:p.store||'متجر خارجي',affiliate:p.affiliate_url||'',image:p.image_url||'',description:p.description||'',stock:p.stock??999,rating:+p.rating||0,reviews:+p.review_count||0}));renderProducts();buildStoreFilter();if(isAdmin)renderAdmin()}
function buildStoreFilter(){const stores=[...new Set(products.map(p=>p.store).filter(Boolean))];$('storeFilter').innerHTML='<option value="">كل المتاجر</option>'+stores.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('')}
function getList(){let a=activeCat==='الكل'?[...products]:products.filter(p=>p.cat===activeCat);const q=$('productSearch').value.trim().toLowerCase(),min=+$('minPrice').value||0,max=+$('maxPrice').value||Infinity,store=$('storeFilter').value; if(q)a=a.filter(p=>(p.name+' '+p.description+' '+p.store).toLowerCase().includes(q));a=a.filter(p=>p.price>=min&&p.price<=max&&(!store||p.store===store));const s=$('sort').value;if(s==='low')a.sort((x,y)=>x.price-y.price);if(s==='high')a.sort((x,y)=>y.price-x.price);if(s==='discount')a.sort((x,y)=>((y.old-y.price)/(y.old||1))-((x.old-x.price)/(x.old||1)));return a}
function renderProducts(){const list=getList();$('productsGrid').innerHTML=list.map(card).join('')||'<div class="empty">لا توجد منتجات مطابقة.</div>'}
function card(p){const d=p.old>p.price?Math.round((1-p.price/p.old)*100):0;return `<article class="product"><button class="heart" onclick="toggleFav(${p.id})">${favorites.has(p.id)?'♥':'♡'}</button><button class="productOpen" onclick="openProduct(${p.id})"><div class="pimg">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy">`:'🛍️'}</div><div class="pbody"><small>${esc(p.store)}</small><h3>${esc(p.name)}</h3><div class="stars">${p.rating?'★'.repeat(Math.round(p.rating)):'☆'} <span>${p.reviews?`(${p.reviews})`:'جديد'}</span></div><div class="pprice">${money(p.price)} <span>جنيه</span> ${d?`<del>${money(p.old)}</del><em>-${d}%</em>`:''}</div></div></button><div class="pactions"><button onclick="addToCart(${p.id})">أضف للسلة</button>${p.affiliate?safeUrl(p.affiliate)?`<a href="${esc(safeUrl(p.affiliate))}" target="_blank" rel="nofollow sponsored noopener" onclick="trackAffiliate(${p.id})">شراء من المتجر ↗</a>`:'':''}</div></article>`}
function filterCat(c){activeCat=c;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.textContent===c));renderProducts();$('products').scrollIntoView({behavior:'smooth'})}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const d=p.old>p.price?Math.round((1-p.price/p.old)*100):0;$('productDetail').innerHTML=`<div class="detail"><div class="detailImg">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:'🛍️'}</div><div><span class="tag">${esc(p.store)}</span><h2>${esc(p.name)}</h2><div class="stars big">${p.rating?'★'.repeat(Math.round(p.rating)):'☆'} <span>${p.reviews?`${p.reviews} تقييم`:'لا توجد تقييمات'}</span></div><p>${esc(p.description||'وصف المنتج غير متوفر حاليًا.')}</p><div class="detailPrice">${money(p.price)} جنيه ${d?`<del>${money(p.old)}</del><em>خصم ${d}%</em>`:''}</div><div class="detailBtns"><button class="primary" onclick="addToCart(${p.id});closeModal('productModal')">أضف للسلة</button>${p.affiliate&&safeUrl(p.affiliate)?`<a class="secondary" href="${esc(safeUrl(p.affiliate))}" target="_blank" rel="nofollow sponsored noopener" onclick="trackAffiliate(${p.id})">شراء من المتجر الأصلي ↗</a>`:''}</div></div></div>`;openModal('productModal')}
async function trackAffiliate(id){if(sb&&currentUser)await sb.from('affiliate_clicks').insert({user_id:currentUser.id,product_id:id}).catch(()=>{})}
function toggleFav(id){if(!currentUser){toast('سجّل دخولك أولًا لحفظ المفضلة');openAccount();return}favorites.has(id)?favorites.delete(id):favorites.add(id);saveLocal();renderProducts();toast(favorites.has(id)?'تمت إضافة المنتج للمفضلة':'تمت إزالة المنتج')}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;const i=cart.find(x=>x.id===id);if(i)i.qty++;else cart.push({...p,qty:1});saveLocal();updateCart();toast('تمت إضافة المنتج للسلة')}
function updateCart(){const n=cart.reduce((s,x)=>s+x.qty,0);$('cartCount').textContent=n;$('cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cartItem"><div class="thumb">${x.image?`<img src="${esc(x.image)}">`:'🛍️'}</div><div class="ci"><b>${esc(x.name)}</b><small>${money(x.price)} جنيه</small><div><button onclick="qty(${x.id},-1)">−</button>${x.qty}<button onclick="qty(${x.id},1)">+</button></div></div><button class="remove" onclick="removeCart(${x.id})">×</button></div>`).join(''):'<div class="empty">السلة فارغة.</div>';$('cartTotal').textContent=money(cart.reduce((s,x)=>s+x.price*x.qty,0))}
function qty(id,d){const x=cart.find(p=>p.id===id);if(!x)return;x.qty=Math.max(1,x.qty+d);saveLocal();updateCart()}function removeCart(id){cart=cart.filter(x=>x.id!==id);saveLocal();updateCart()}
function openCart(){$('cart').classList.add('open');$('shade').classList.add('show')}function closeCart(){$('cart').classList.remove('open');$('shade').classList.remove('show')}
function toggleMenu(){document.body.classList.toggle('menu-open')}function closeMenu(){document.body.classList.remove('menu-open')}
function openAccount(){closeMenu();renderAccountView();openModal('accountModal')}
function renderAccount(){const x=$('accountBtn');x.innerHTML=currentUser?`<span>👤</span><small>${esc((currentUser.profile?.full_name||currentUser.email||'حساب').split('@')[0])}</small>`:'<span>👤</span><small>تسجيل الدخول</small>';}
function renderAccountView(){if(!currentUser){$('accountView').innerHTML=`<div class="authLogo">👤</div><h2>${registerMode?'إنشاء حساب جديد':'تسجيل الدخول'}</h2><p class="muted">حسابك يحفظ المفضلة والطلبات والتتبع.</p><form id="authForm"><div class="switch"><button type="button" class="${!registerMode?'on':''}" onclick="switchAuth(false)">دخول</button><button type="button" class="${registerMode?'on':''}" onclick="switchAuth(true)">اشتراك</button></div>${registerMode?'<input id="authName" placeholder="الاسم الكامل" required>':''}<input id="authEmail" type="email" autocomplete="email" placeholder="البريد الإلكتروني" required><input id="authPassword" type="password" autocomplete="current-password" minlength="6" placeholder="كلمة المرور" required><button class="primary full">${registerMode?'إنشاء الحساب':'دخول'}</button></form><div id="authStatus" class="authStatus"></div>${!registerMode?'<button class="textBtn" onclick="forgotPassword()">نسيت كلمة المرور؟</button>':''}`;$('authForm').onsubmit=handleAuth;return}const p=currentUser.profile||{};$('accountView').innerHTML=`<div class="profileHead"><div class="avatar">👤</div><div><h2>أهلًا ${esc(p.full_name||'بك')}</h2><p>${esc(currentUser.email)}</p></div></div><div class="accountMenu"><button onclick="showOrders()">📦 طلباتي <span>›</span></button><button onclick="showFavorites()">❤️ المفضلة <span>${favorites.size}</span></button><button onclick="showProfile()">⚙️ بيانات وإعدادات الحساب <span>›</span></button><button onclick="showTrackBox()">🚚 تتبع الشحنة <span>›</span></button>${isAdmin?'<button class="adminAccountBtn" onclick="closeModal(\'accountModal\');openAdmin()">🛠️ لوحة الإدارة <span>مدير</span></button>':''}</div><button class="secondary full" onclick="signOut()">تسجيل الخروج</button>`}
function switchAuth(v){registerMode=v;renderAccountView()}
async function handleAuth(e){e.preventDefault();if(!sb){setAuthStatus('Supabase غير مربوط. راجع ملف الإعداد.');return}const email=$('authEmail').value.trim().toLowerCase(),password=$('authPassword').value,name=$('authName')?.value.trim()||'';setAuthStatus('جاري الاتصال...');let r;if(registerMode)r=await sb.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:window.FARTAKA_SITE_URL||'https://mohmdfartka00-collab.github.io/fartkaa/'}});else r=await sb.auth.signInWithPassword({email,password});if(r.error){console.error(r.error);setAuthStatus(r.error.message);toast('فشل تسجيل الدخول/الاشتراك','error');return}if(registerMode&&!r.data.session){setAuthStatus('تم إنشاء الحساب. افتح رسالة تأكيد البريد ثم ارجع وسجّل الدخول.',true);return}if(r.data.user){await ensureProfile(r.data.user,name);await setUser(r.data.user);toast(registerMode?'تم إنشاء الحساب بنجاح':'تم تسجيل الدخول بنجاح','ok');closeModal('accountModal')}}
async function ensureProfile(user,name=''){if(!sb||!user)return;const {error}=await sb.from('profiles').upsert({id:user.id,full_name:name||user.user_metadata?.full_name||''},{onConflict:'id'});if(error)console.warn('profile upsert',error.message)}
async function forgotPassword(){if(!sb){toast('Supabase غير مربوط بالموقع','error');return}const email=prompt('اكتب بريدك الإلكتروني لاستعادة كلمة المرور');if(!email)return;const clean=email.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(clean)){toast('اكتب بريدًا إلكترونيًا صحيحًا','error');return}const redirectTo='https://mohmdfartka00-collab.github.io/fartkaa/reset.html';toast('جاري إرسال رسالة الاستعادة...');const {error}=await sb.auth.resetPasswordForEmail(clean,{redirectTo});if(error){console.error('resetPasswordForEmail',error);const msg=String(error.message||'');if(error.status===429||/rate|too many|limit|60 seconds|2 emails/i.test(msg))toast('Supabase أوقف إرسال الرسائل مؤقتًا بسبب حد الإرسال. انتظر حتى يُسمح بإرسال رسالة جديدة أو اربط SMTP مخصصًا.','error');else toast('تعذر إرسال الرسالة: '+msg,'error');return}toast('تم طلب رسالة الاستعادة. راجع البريد والرسائل غير المرغوب فيها.','ok')}
async function signOut(){if(sb)await sb.auth.signOut();currentUser=null;isAdmin=false;renderAccount();renderAccountView();toast('تم تسجيل الخروج')}
function showOrders(){if(!currentUser){toast('سجّل الدخول أولًا');return}const box=$('accountView');box.innerHTML='<h2>طلباتي</h2><div id="myOrders">جاري التحميل...</div><button class="textBtn" onclick="renderAccountView()">← رجوع</button>';loadMyOrders()}
async function loadMyOrders(){const {data,error}=await sb.from('orders').select('id,order_number,tracking_number,total,status,payment_status,created_at').eq('user_id',currentUser.id).order('created_at',{ascending:false});$('myOrders').innerHTML=error?`<div class="errorBox">${esc(error.message)}</div>`:(data||[]).map(o=>`<button class="orderCard" onclick="showOrder('${o.id}')"><div><b>${esc(o.order_number)}</b><small>${new Date(o.created_at).toLocaleDateString('ar-EG')}</small></div><strong>${money(o.total)} ج</strong><span class="status">${statusText(o.status)}</span></button>`).join('')||'<div class="empty">لا توجد طلبات بعد.</div>'}
async function showOrder(id){const {data:o}=await sb.from('orders').select('*').eq('id',id).maybeSingle();if(!o)return;const {data:ev}=await sb.from('shipping_events').select('*').eq('order_id',id).order('event_time',{ascending:true});$('accountView').innerHTML=`<h2>تفاصيل الطلب ${esc(o.order_number)}</h2><p class="muted">رقم التتبع: <b>${esc(o.tracking_number||'غير متاح')}</b></p><div class="timeline">${['pending_payment','paid','processing','shipped','out_for_delivery','delivered'].map(s=>`<div class="tl ${isDone(o.status,s)?'done':''}"><span>✓</span><b>${statusText(s)}</b></div>`).join('')}</div><div class="events">${(ev||[]).map(e=>`<div><b>${statusText(e.status)}</b><small>${new Date(e.event_time).toLocaleString('ar-EG')}</small><p>${esc(e.note||'')}</p></div>`).join('')}</div><button class="textBtn" onclick="showOrders()">← رجوع</button>`}
const orderRank={pending_payment:0,paid:1,processing:2,shipped:3,out_for_delivery:4,delivered:5};function isDone(cur,s){return (orderRank[cur]??0)>=(orderRank[s]??0)}function statusText(s){return ({pending_payment:'في انتظار الدفع',paid:'تم الدفع',processing:'قيد التجهيز',shipped:'تم الشحن',out_for_delivery:'خرج للتوصيل',delivered:'تم التسليم',cancelled:'ملغي'})[s]||s}
function showFavorites(){const list=products.filter(p=>favorites.has(p.id));$('accountView').innerHTML=`<h2>المفضلة ❤️</h2>${list.map(p=>`<div class="favRow"><img src="${esc(p.image||'logo.svg')}"><span>${esc(p.name)}</span><button onclick="openProduct(${p.id})">عرض</button></div>`).join('')||'<div class="empty">مفيش منتجات محفوظة.</div>'}<button class="textBtn" onclick="renderAccountView()">← رجوع</button>`}
function showProfile(){const p=currentUser.profile||{};$('accountView').innerHTML=`<h2>بيانات الحساب</h2><form id="profileForm"><input id="pfName" value="${esc(p.full_name||'')}" placeholder="الاسم"><input id="pfPhone" value="${esc(p.phone||'')}" placeholder="رقم الهاتف"><input id="pfCity" value="${esc(p.city||'')}" placeholder="المدينة"><textarea id="pfAddress" placeholder="العنوان">${esc(p.address||'')}</textarea><button class="primary full">حفظ البيانات</button></form><button class="textBtn" onclick="renderAccountView()">← رجوع</button>`;$('profileForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('profiles').update({full_name:$('pfName').value.trim(),phone:$('pfPhone').value.trim(),city:$('pfCity').value.trim(),address:$('pfAddress').value.trim()}).eq('id',currentUser.id);if(error)toast(error.message,'error');else{await setUser(currentUser);toast('تم حفظ البيانات','ok');renderAccountView()}}}
function showTrackBox(){ $('accountView').innerHTML=`<h2>تتبع الشحنة 🚚</h2><form onsubmit="track(event)"><input id="trackInput" placeholder="رقم الطلب أو رقم التتبع" required><button class="primary full">تتبع</button></form><div id="trackResult"></div><button class="textBtn" onclick="renderAccountView()">← رجوع</button>`}
async function track(e){e.preventDefault();const q=$('trackInput').value.trim();const {data,error}=await sb.from('orders').select('id,order_number,tracking_number,status,total,created_at').or(`order_number.eq.${q},tracking_number.eq.${q}`).maybeSingle();if(error||!data){$('trackResult').innerHTML='<div class="errorBox">لم نجد طلبًا بهذا الرقم.</div>';return}const {data:ev}=await sb.from('shipping_events').select('*').eq('order_id',data.id).order('event_time',{ascending:true});$('trackResult').innerHTML=`<div class="trackCard"><b>${esc(data.order_number)}</b><p>التتبع: ${esc(data.tracking_number||'')}</p><div class="timeline">${['pending_payment','paid','processing','shipped','out_for_delivery','delivered'].map(s=>`<div class="tl ${isDone(data.status,s)?'done':''}"><span>✓</span><b>${statusText(s)}</b></div>`).join('')}</div>${(ev||[]).map(x=>`<div class="event"><b>${statusText(x.status)}</b><small>${new Date(x.event_time).toLocaleString('ar-EG')}</small></div>`).join('')}</div>`}
function showTrackPublic(){openModal('trackModal');setTimeout(()=>$('trackInputModal')?.focus(),0)}
async function publicTrack(e){e.preventDefault();const field=e.currentTarget.querySelector('input');const q=field.value.trim();if(!sb)return;const {data,error}=await sb.from('orders').select('id,order_number,tracking_number,status,total,created_at').or(`order_number.eq.${q},tracking_number.eq.${q}`).maybeSingle();$('publicTrackResult').innerHTML=error||!data?'<div class="errorBox">لم نجد الطلب. تأكد من الرقم.</div>':`<div class="trackCard"><h3>${esc(data.order_number)}</h3><p>رقم التتبع: ${esc(data.tracking_number||'')}</p><div class="timeline">${['pending_payment','paid','processing','shipped','out_for_delivery','delivered'].map(s=>`<div class="tl ${isDone(data.status,s)?'done':''}"><span>✓</span><b>${statusText(s)}</b></div>`).join('')}</div></div>`}
function openSearch(){openModal('searchModal');$('globalSearch').focus()}function doSearch(){const q=$('globalSearch').value.toLowerCase();$('searchResults').innerHTML=products.filter(p=>(p.name+' '+p.store).toLowerCase().includes(q)).slice(0,10).map(p=>`<button onclick="closeModal('searchModal');openProduct(${p.id})"><img src="${esc(p.image||'logo.svg')}"><span>${esc(p.name)}</span><b>${money(p.price)} ج</b></button>`).join('')||'<div class="empty">لا توجد نتائج.</div>'}
async function openAdmin(){if(!isAdmin){toast('هذا القسم للمدير فقط','error');return}closeMenu();renderAdmin();openModal('adminModal')}
function renderAdmin(){if(!isAdmin)return;$('adminProducts').innerHTML=`<div class="adminHead"><div><h3>منتجات الأفليت</h3><p>أضف رابط الأفليت والصورة والوصف والسعر من مكان واحد.</p></div><button class="primary" onclick="showProductForm()">＋ إضافة منتج أفليت</button></div><div class="adminList">${products.map(p=>`<div class="adminProduct"><img src="${esc(p.image||'logo.svg')}"><div><b>${esc(p.name)}</b><small>${esc(p.store)} • ${money(p.price)} ج</small><small class="link">${esc(p.affiliate||'بدون رابط أفليت')}</small></div><button onclick="showProductForm(${p.id})">تعديل</button><button class="danger" onclick="deleteProduct(${p.id})">حذف</button></div>`).join('')||'<div class="empty">لا توجد منتجات.</div>'}</div>`}
const oldRenderAdmin=renderAdmin;renderAdmin=function(){oldRenderAdmin();if(!isAdmin)return;$('adminHeroTitle').value=siteSettings.hero_title||'';$('adminHeroText').value=siteSettings.hero_text||'';$('adminFooterText').value=siteSettings.footer_text||'منصة تسوق وأفليت مصرية بتجربة حديثة.';$('siteMediaPreview').innerHTML=[siteSettings.logo_image,...(siteSettings.category_images||[])].filter(Boolean).map(x=>`<img src="${esc(x)}">`).join('')};
function showProductForm(id){const p=products.find(x=>x.id===id)||{};$('productEditor').innerHTML=`<div class="editor"><h3>${id?'تعديل المنتج':'إضافة منتج أفليت جديد'}</h3><form id="productForm"><div class="formGrid"><label>اسم المنتج<input id="fName" value="${esc(p.name||'')}" required></label><label>المتجر الأصلي<input id="fStore" value="${esc(p.store||'')}" placeholder="Amazon / noon ..."></label><label>رابط الأفليت *<input id="fAffiliate" type="url" value="${esc(p.affiliate||'')}" required placeholder="ضع رابط الأفليت هنا"></label><label>رابط الصورة (اختياري)<input id="fImageUrl" type="url" value="${esc(p.image||'')}" placeholder="أو استخدم رفع الصورة"></label><label>رفع صورة المنتج *<input id="fImage" type="file" accept="image/png,image/jpeg,image/webp" ${p.image?'':'required'}></label><label>السعر<input id="fPrice" type="number" min="0" step="0.01" value="${p.price||0}" required></label><label>السعر قبل الخصم<input id="fOld" type="number" min="0" step="0.01" value="${p.old||p.price||0}"></label><label>القسم<input id="fCat" value="${esc(p.cat||'مستلزمات')}"></label><label>المخزون<input id="fStock" type="number" min="0" value="${p.stock??999}"></label><label class="full">وصف المنتج<textarea id="fDesc" rows="5" placeholder="اكتب وصف المنتج بالتفصيل...">${esc(p.description||'')}</textarea></label></div><div class="preview" id="imagePreview">${p.image?`<img src="${esc(p.image)}">`:'معاينة صورة المنتج'}</div><div class="formActions"><button class="primary">${id?'حفظ التعديل':'إضافة المنتج'}</button><button type="button" class="secondary" onclick="$('productEditor').innerHTML=''">إلغاء</button></div><div id="uploadStatus" class="authStatus"></div></form></div>`;$('fImage').onchange=e=>{const f=e.target.files[0];if(f){$('imagePreview').innerHTML=`<img src="${URL.createObjectURL(f)}">`}};$('productForm').onsubmit=e=>saveProduct(e,id)}
async function uploadProductImage(file){if(!sb||!currentUser||!isAdmin)throw new Error('يجب تسجيل الدخول كمدير');if(!file)throw new Error('لم تختار صورة');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('الصورة يجب أن تكون JPG أو PNG أو WEBP');if(file.size>8*1024*1024)throw new Error('حجم الصورة أكبر من 8 ميجابايت');const ext=file.type.split('/')[1].replace('jpeg','jpg');const path=`products/${currentUser.id}/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('product-images').upload(path,file,{contentType:file.type,upsert:false,cacheControl:'31536000'});if(error)throw new Error('رفع الصورة فشل: '+error.message);const {data}=sb.storage.from('product-images').getPublicUrl(path);return data.publicUrl}
async function saveProduct(e,id){e.preventDefault();const status=$('uploadStatus');status.textContent='جاري الحفظ...';try{let image=$('fImageUrl').value.trim();const file=$('fImage').files[0];if(file)image=await uploadProductImage(file);if(!safeUrl($('fAffiliate').value.trim()))throw new Error('رابط الأفليت غير صحيح');if(!image)throw new Error('لازم ترفع صورة المنتج أو تضع رابط صورة');const payload={name:$('fName').value.trim(),store:$('fStore').value.trim(),affiliate_url:$('fAffiliate').value.trim(),image_url:image,price:+$('fPrice').value,old_price:+$('fOld').value||+$('fPrice').value,category:$('fCat').value.trim(),stock:+$('fStock').value,description:$('fDesc').value.trim()};const r=id?await sb.from('products').update(payload).eq('id',id):await sb.from('products').insert(payload);if(r.error)throw new Error(r.error.message);toast(id?'تم تعديل المنتج':'تمت إضافة منتج الأفليت بنجاح','ok');$('productEditor').innerHTML='';await loadProducts()}catch(err){status.textContent=err.message;toast(err.message,'error')}}
async function deleteProduct(id){if(!confirm('هل تريد حذف المنتج؟'))return;const {error}=await sb.from('products').delete().eq('id',id);if(error)toast(error.message,'error');else{toast('تم حذف المنتج','ok');await loadProducts()}}
async function saveSite(){if(!isAdmin)return;try{const payload={hero_title:$('adminHeroTitle').value.trim(),hero_text:$('adminHeroText').value.trim(),footer_text:$('adminFooterText').value.trim()};const logoFile=$('adminLogoFile').files[0];const heroFile=$('adminHeroFile').files[0];if(logoFile)payload.logo_image=await uploadProductImage(logoFile);if(heroFile)payload.hero_image=await uploadProductImage(heroFile);const imgs=[0,1,2,3,4,5,6].map(i=>$('catImg'+i)?.files[0]);let categoryImages=[...(siteSettings.category_images||[])];for(let i=0;i<imgs.length;i++){if(imgs[i])categoryImages[i]=await uploadProductImage(imgs[i])}payload.category_images=categoryImages;const r=siteSettings.id?await sb.from('site_settings').update(payload).eq('id',siteSettings.id):await sb.from('site_settings').insert(payload);if(r.error)throw new Error(r.error.message);toast('تم حفظ كل تعديلات الصور والواجهة','ok');await loadSite();renderAdmin()}catch(e){toast(e.message,'error')}}
function goProducts(){closeMenu();$('products').scrollIntoView({behavior:'smooth'})}
function initEvents(){
  $('menuBtn').onclick=toggleMenu;$('menuClose').onclick=closeMenu;$('shade').onclick=closeCart;$('cartBtn').onclick=openCart;$('accountBtn').onclick=openAccount;$('searchBtn').onclick=openSearch;$('globalSearch').oninput=doSearch;$('productSearch').oninput=renderProducts;$('sort').onchange=renderProducts;$('minPrice').oninput=renderProducts;$('maxPrice').oninput=renderProducts;$('storeFilter').onchange=renderProducts;$('trackForm').onsubmit=publicTrack;
}
initEvents();init();
