let sb=null;
const cfg=window.FARTAKA_SUPABASE_CONFIG||{}, payCfg=window.FARTAKA_PAYMENT_CONFIG||{};
if(window.supabase&&cfg.supabase_url&&cfg.supabase_publishable_key){sb=window.supabase.createClient(cfg.supabase_url,cfg.supabase_publishable_key)}
const cats=[['الكل','✨'],['إلكترونيات','📱'],['منزل','🏠'],['أزياء','👕'],['أطفال','🧸'],['رياضة','⚽'],['جمال','💄'],['مستلزمات','🧰']];
let products=[],activeCat='الكل',cart=JSON.parse(localStorage.getItem('fartaka_cart')||'[]'),favorites=new Set(JSON.parse(localStorage.getItem('fartaka_favorites')||'[]')),currentUser=null,isAdmin=false,visibleCount=12,coupon=null,siteSettings={},registerMode=false;
const $=id=>document.getElementById(id);
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function money(n){return Number(n||0).toLocaleString('ar-EG',{maximumFractionDigits:2})}
function toast(t){const x=$('toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>x.classList.remove('show'),3500)}
function openModal(id){const el=$(id);if(!el)return;el.hidden=false;el.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}
function closeModal(id){const el=$(id);if(!el)return;el.hidden=true;el.setAttribute('aria-hidden','true');if(!document.querySelector('.modal:not([hidden])'))document.body.classList.remove('modal-open')}
function closeSearch(){closeModal('searchModal')}
function closeMenu(){$('sideMenu').classList.remove('open');$('menuOverlay').classList.remove('show')}
function openMenu(){renderMenuUser();$('sideMenu').classList.add('open');$('menuOverlay').classList.add('show')}
function saveLocal(){localStorage.setItem('fartaka_cart',JSON.stringify(cart));localStorage.setItem('fartaka_favorites',JSON.stringify([...favorites]))}
function idArg(id){return JSON.stringify(String(id))}
async function init(){
  $('categoriesGrid').innerHTML=cats.slice(1).map(c=>`<button class="category" onclick='filterCat(${idArg(c[0])})'><div class="ico">${c[1]}</div><b>${esc(c[0])}</b></button>`).join('');
  $('chips').innerHTML=cats.map(c=>`<button class="chip ${c[0]==='الكل'?'active':''}" onclick='filterCat(${idArg(c[0])})'>${c[1]} ${esc(c[0])}</button>`).join('');
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();document.querySelectorAll('.modal:not([hidden])').forEach(m=>closeModal(m.id));}});
  document.querySelectorAll('.modal').forEach(m=>{m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)});m.querySelector('.close')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();closeModal(m.id)})});
  if(sb){const {data:{session}}=await sb.auth.getSession();if(session)await setUser(session.user);sb.auth.onAuthStateChange((_e,s)=>{setUser(s?.user||null)})}
  await loadSite();await loadProducts();updateCart();renderAccount();renderMenuUser();handlePaymentReturn();
}
async function setUser(user){currentUser=user||null;isAdmin=false;if(user&&sb){const {data}=await sb.from('profiles').select('full_name,phone,address,city,role').eq('id',user.id).maybeSingle();isAdmin=data?.role==='admin'}renderAccount();renderMenuUser();if($('adminBtn'))$('adminBtn').hidden=!isAdmin;if($('menuAdmin'))$('menuAdmin').hidden=!isAdmin}
function renderMenuUser(){$('menuUser').innerHTML=currentUser?`<div class="menuUser"><div class="avatar">👤</div><div><b>${esc(currentUser.email)}</b><small>${isAdmin?'مدير المتجر':'عميل فرتكه'}</small></div></div>`:`<div class="menuGuest">👋 أهلًا بيك في فرتكه<br><small>سجّل دخولك أو اعمل حساب جديد</small></div>`}
async function loadSite(){if(!sb)return;const {data}=await sb.from('site_settings').select('*').limit(1).maybeSingle();if(data){siteSettings=data;if(data.hero_title)document.querySelector('.hero h1').innerHTML=esc(data.hero_title).replace(/\n/g,'<br>');if(data.hero_text)document.querySelector('.hero p').textContent=data.hero_text;if(data.hero_image)applySiteImage()}}
async function loadProducts(){if(!sb){toast('الاتصال بقاعدة البيانات غير جاهز');return}const {data,error}=await sb.from('products').select('*').order('created_at',{ascending:false});if(error){console.error(error);toast('حصل خطأ في تحميل المنتجات: '+error.message);return}products=(data||[]).map(p=>({id:p.id,name:p.name,price:+p.price,old:+(p.old_price||p.price),cat:p.category||'عام',source:p.store||'متجر خارجي',url:p.affiliate_url||'',description:p.description||'',image:p.image_url||'',emoji:'🛍️',stock:p.stock??999,rating:+(p.rating||0),reviews:+(p.review_count||0)}));buildStoreFilter();renderProducts();if(isAdmin)renderAdmin()}
function buildStoreFilter(){const stores=[...new Set(products.map(p=>p.source).filter(Boolean))];$('storeFilter').innerHTML='<option value="">كل المتاجر</option>'+stores.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('')}
function getList(){let list=activeCat==='الكل'?[...products]:products.filter(p=>p.cat===activeCat);const min=+$('minPrice').value||0,max=+$('maxPrice').value||Infinity,store=$('storeFilter').value,sale=$('saleOnly').checked;list=list.filter(p=>p.price>=min&&p.price<=max&&(!store||p.source===store)&&(!sale||p.old>p.price));const s=$('sort').value;if(s==='low')list.sort((a,b)=>a.price-b.price);if(s==='high')list.sort((a,b)=>b.price-a.price);if(s==='discount')list.sort((a,b)=>((b.old-b.price)/b.old)-((a.old-a.price)/a.old));return list}
function renderProducts(){const list=getList(),grid=$('productsGrid');grid.innerHTML=list.slice(0,visibleCount).map(card).join('')||'<div class="empty">مفيش منتجات مطابقة للفلاتر.</div>';$('moreBtn').hidden=list.length<=visibleCount}
function showMore(){visibleCount+=12;renderProducts()}
function safeAffiliate(url){try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)?u.href:'#'}catch{return '#'}}
function affiliateButton(p,cls='btn ghost'){const url=safeAffiliate(p.url);return url==='#'?'<button class="btn ghost" disabled>رابط الشراء غير متاح</button>':`<a class="${cls}" href="${esc(url)}" target="_blank" rel="nofollow sponsored noopener" onclick='trackAffiliateClick(${idArg(p.id)})'>شراء من المتجر الأصلي ↗</a>`}
async function trackAffiliateClick(id){if(sb&&currentUser){try{await sb.from('affiliate_clicks').insert({user_id:currentUser.id,product_id:id})}catch(e){}}}
function card(p){const visual=p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy">`:p.emoji;const discount=p.old>p.price?Math.round((1-p.price/p.old)*100):0;const fav=favorites.has(String(p.id))||favorites.has(p.id)?'♥':'♡';return `<article class="card"><button class="fav" onclick='toggleFav(${idArg(p.id)})'>${fav}</button><span class="source">${esc(p.source)}</span><button class="cardClick" onclick='openProduct(${idArg(p.id)})'><div class="cardImg">${visual}</div><div class="cardBody"><small>${esc(p.cat)}</small><h3>${esc(p.name)}</h3><div class="rating">${p.rating?'★'.repeat(Math.min(5,Math.round(p.rating))):'☆'} <span>${p.reviews?`(${p.reviews})`:'جديد'}</span></div>${discount?`<span class="discount">خصم ${discount}%</span>`:''}<div class="price">${money(p.price)} ج ${p.old>p.price?`<span class="old">${money(p.old)} ج</span>`:''}</div></div></button><div class="cardActions"><button class="add" onclick='addToCart(${idArg(p.id)})'>🛒 للسلة</button>${affiliateButton(p,'buy')}</div></article>`}
function filterCat(cat){activeCat=cat;visibleCount=12;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.textContent.includes(cat)));renderProducts();$('products').scrollIntoView({behavior:'smooth'})}
function toggleFilters(){$('filters').hidden=!$('filters').hidden}
async function toggleFav(id){const key=String(id);if(!currentUser){toast('سجّل الدخول عشان تحفظ المفضلة');openAccount();return}favorites.has(key)?favorites.delete(key):favorites.add(key);saveLocal();renderProducts();if(sb){if(favorites.has(key))await sb.from('favorites').upsert({user_id:currentUser.id,product_id:Number(id)});else await sb.from('favorites').delete().eq('user_id',currentUser.id).eq('product_id',Number(id))}toast(favorites.has(key)?'تمت الإضافة للمفضلة':'تمت الإزالة من المفضلة')}
function addToCart(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;if(p.stock<=0){toast('المنتج غير متاح حاليًا');return}const item=cart.find(x=>String(x.id)===String(id));if(item)item.qty=(item.qty||1)+1;else cart.push({...p,qty:1});saveLocal();updateCart();toast('تمت إضافة المنتج للسلة')}
function removeCart(id){cart=cart.filter(x=>String(x.id)!==String(id));saveLocal();updateCart()}
function changeQty(id,d){const x=cart.find(p=>String(p.id)===String(id));if(!x)return;x.qty=Math.max(1,(x.qty||1)+d);saveLocal();updateCart()}
function subtotal(){return cart.reduce((s,p)=>s+p.price*(p.qty||1),0)}
function updateCart(){const count=cart.reduce((s,p)=>s+(p.qty||1),0);$('count').textContent=count;$('cartItems').innerHTML=cart.length?cart.map(p=>`<div class="cartRow"><div class="cartThumb">${p.image?`<img src="${esc(p.image)}">`:'🛍️'}</div><div class="cartInfo"><b>${esc(p.name)}</b><small>${money(p.price)} ج</small><div class="qty"><button onclick='changeQty(${idArg(p.id)},-1)'>−</button><b>${p.qty||1}</b><button onclick='changeQty(${idArg(p.id)},1)'>+</button></div></div><button class="remove" onclick='removeCart(${idArg(p.id)})'>×</button></div>`).join(''):'<div class="empty">السلة فاضية. اختار منتج وابدأ التسوق.</div>';let total=subtotal();if(coupon?.percent)total*=1-coupon.percent/100;$('total').textContent=money(total)}
function openCart(){$('cartDrawer').classList.add('open');$('overlay').classList.add('show');updateCart()}function closeCart(){$('cartDrawer').classList.remove('open');$('overlay').classList.remove('show')}
function openSearch(){openModal('searchModal');setTimeout(()=>$('searchInput')?.focus(),0);searchProducts()}function searchProducts(){const q=$('searchInput').value.trim().toLowerCase();const list=products.filter(p=>(p.name+' '+p.cat+' '+p.source+' '+p.description).toLowerCase().includes(q));$('searchResults').innerHTML=list.slice(0,20).map(p=>`<div class="result"><div><b>${esc(p.name)}</b><small>${esc(p.source)} • ${money(p.price)} ج</small></div><button class="btn" onclick='openProduct(${idArg(p.id)});closeSearch()'>عرض</button></div>`).join('')||'<div class="empty">مفيش نتائج.</div>'}
function quickSearch(){const q=$('topSearch').value.trim();if(q.length>=2){openSearch();$('searchInput').value=q;searchProducts()}}
function openProduct(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;$('productDetail').innerHTML=`<div class="productDetail"><div class="detailImage">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:p.emoji}</div><div class="detailInfo"><small>${esc(p.cat)} • ${esc(p.source)}</small><h2>${esc(p.name)}</h2><p>${esc(p.description||'لا يوجد وصف مضاف حاليًا.')}</p><div class="detailPrice">${money(p.price)} ج ${p.old>p.price?`<del>${money(p.old)} ج</del>`:''}</div><div class="detailActions"><button class="btn primary" onclick='addToCart(${idArg(p.id)});closeModal("productModal")'>🛒 أضف للسلة</button>${affiliateButton(p,'btn ghost')}</div><div class="affiliateInfo">🔗 الشراء يتم من المتجر الأصلي عبر رابط الأفليت.</div></div></div>`;openModal('productModal')}
function openAccount(){renderAccountView();openModal('accountModal')}
function openAccountRegister(){renderAccountView();registerMode=true;openModal('accountModal');setTimeout(()=>{const b=$('registerMode');if(b)b.click()},0)}
function renderAccount(){const a=document.querySelector('.actions button:not(.menuBtn)');if(a)a.title=currentUser?`حساب ${currentUser.email}`:'تسجيل الدخول'}
function renderAccountView(){if(!currentUser){$('accountView').innerHTML=`<h2>حسابك في فرتكه</h2><p>سجّل دخولك أو اعمل حساب جديد عشان تحفظ المفضلة وتطلب وتتابع الشحنات.</p><form id="authForm"><div class="authSwitch"><button type="button" id="loginMode" class="active">تسجيل الدخول</button><button type="button" id="registerMode">إنشاء حساب</button></div><input id="authName" placeholder="الاسم" hidden><input id="authEmail" type="email" placeholder="البريد الإلكتروني" autocomplete="email" required><input id="authPassword" type="password" minlength="6" placeholder="كلمة المرور (6 أحرف على الأقل)" autocomplete="current-password" required><button class="btn primary fullBtn">متابعة</button></form><button class="linkBtn" onclick="forgotPassword()">نسيت كلمة المرور؟</button><button class="linkBtn" onclick="resendConfirmation()">إعادة إرسال تأكيد البريد</button><div class="authHelp">لو التسجيل بيقولك راجع بريدك، لازم تضغط رابط التأكيد في رسالة Supabase قبل أول تسجيل دخول.</div>`;bindAuthModes();return}$('accountView').innerHTML=`<div class="accountHead"><div class="avatar">👤</div><div><h2>أهلًا بيك</h2><p>${esc(currentUser.email)}</p></div></div><div class="accountCards"><button onclick="myOrders()">📦<b>طلباتي</b><small>تتبع كل طلباتك</small></button><button onclick="openFavoritesModal()">❤️<b>المفضلة</b><small>${favorites.size} منتج</small></button><button onclick="openSettings()">⚙️<b>بياناتي</b><small>العنوان والهاتف</small></button></div><button class="btn ghost fullBtn" onclick="signOut()">تسجيل الخروج</button>`}
function bindAuthModes(){registerMode=false;$('loginMode').onclick=()=>{registerMode=false;$('loginMode').classList.add('active');$('registerMode').classList.remove('active');$('authName').hidden=true;$('authPassword').autocomplete='current-password'};$('registerMode').onclick=()=>{registerMode=true;$('registerMode').classList.add('active');$('loginMode').classList.remove('active');$('authName').hidden=false;$('authPassword').autocomplete='new-password'};$('authForm').onsubmit=handleAuth}
async function handleAuth(e){e.preventDefault();if(!sb){toast('الموقع غير متصل بـ Supabase. راجع supabase-config.js');return}const email=$('authEmail').value.trim().toLowerCase(),password=$('authPassword').value,name=$('authName').value.trim();let r;if(registerMode)r=await sb.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:location.origin+location.pathname}});else r=await sb.auth.signInWithPassword({email,password});if(r.error){toast(authError(r.error));return}if(registerMode){if(r.data.session){await setUser(r.data.user);toast('تم إنشاء الحساب وتسجيل الدخول ✅');renderAccountView()}else{toast('تم إنشاء الحساب. افتح رسالة التأكيد في بريدك ثم ارجع وسجّل الدخول.');renderAccountView()}}else{await setUser(r.data.user);toast('تم تسجيل الدخول بنجاح ✅');renderAccountView()}}
function authError(e){const m=e?.message||'حصل خطأ في تسجيل الدخول';if(/email not confirmed/i.test(m))return'البريد الإلكتروني غير مؤكد. افتح رسالة Supabase واضغط رابط التأكيد.';if(/invalid login credentials/i.test(m))return'البريد أو كلمة المرور غير صحيحة.';if(/user already registered/i.test(m))return'البريد ده مسجل بالفعل. جرّب تسجيل الدخول.';return m}
async function resendConfirmation(){if(!sb)return;const email=prompt('اكتب بريدك الإلكتروني لإعادة إرسال رسالة التأكيد');if(!email)return;const r=await sb.auth.resend({type:'signup',email:email.trim().toLowerCase(),options:{emailRedirectTo:location.origin+location.pathname}});toast(r.error?authError(r.error):'تم إرسال رسالة تأكيد جديدة، راجع البريد والرسائل غير المرغوب فيها.')}
async function signOut(){if(sb)await sb.auth.signOut();currentUser=null;isAdmin=false;renderAccountView();renderAccount();renderMenuUser();toast('تم تسجيل الخروج')}
async function forgotPassword(){const email=prompt('اكتب بريدك الإلكتروني');if(!email||!sb)return;const r=await sb.auth.resetPasswordForEmail(email.trim().toLowerCase(),{redirectTo:location.origin+location.pathname});toast(r.error?authError(r.error):'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك')}
async function openSettings(){if(!currentUser){toast('سجّل الدخول أولًا');openAccount();return}const {data}=await sb.from('profiles').select('*').eq('id',currentUser.id).maybeSingle();$('settingsView').innerHTML=`<h2>⚙️ إعدادات الحساب</h2><p>${esc(currentUser.email)}</p><form id="profileForm"><input id="pfName" placeholder="الاسم" value="${esc(data?.full_name||'')}"><input id="pfPhone" placeholder="رقم الهاتف" value="${esc(data?.phone||'')}"><input id="pfAddress" placeholder="العنوان بالتفصيل" value="${esc(data?.address||'')}"><input id="pfCity" placeholder="المحافظة / المدينة" value="${esc(data?.city||'')}"><button class="btn primary fullBtn">حفظ البيانات</button></form>`;$('profileForm').onsubmit=async e=>{e.preventDefault();const r=await sb.from('profiles').upsert({id:currentUser.id,full_name:$('pfName').value.trim(),phone:$('pfPhone').value.trim(),address:$('pfAddress').value.trim(),city:$('pfCity').value.trim()});toast(r.error?r.error.message:'تم حفظ بياناتك');closeModal('settingsModal')};openModal('settingsModal')}
async function myOrders(){if(!currentUser){toast('سجّل الدخول');openAccount();return}const {data,error}=await sb.from('orders').select('id,order_number,total,status,created_at,tracking_number').eq('user_id',currentUser.id).order('created_at',{ascending:false});if(error){toast('تعذر تحميل الطلبات: '+error.message);return}$('accountView').innerHTML=`<h2>📦 طلباتي</h2>${(data||[]).map(o=>`<div class="orderMini"><div><b>${esc(o.order_number)}</b><small>${new Date(o.created_at).toLocaleDateString('ar-EG')} • ${money(o.total)} ج</small></div><span class="status ${esc(o.status)}">${statusText(o.status)}</span><button class="btn" onclick='showTracking(${idArg(o.tracking_number||o.order_number)})'>تتبع</button></div>`).join('')||'<div class="empty">لسه مفيش طلبات.</div>'}<button class="linkBtn" onclick="renderAccountView()">رجوع للحساب</button>`}
function openMyOrders(){openAccount();if(currentUser)myOrders()}
async function openFavoritesModal(){if(!currentUser){toast('سجّل الدخول عشان تشوف المفضلة');openAccount();return}const ids=[...favorites].map(String);const list=products.filter(p=>ids.includes(String(p.id)));$('favoritesView').innerHTML=`<h2>❤️ المفضلة</h2>${list.length?`<div class="favList">${list.map(p=>`<div class="favItem"><span><b>${esc(p.name)}</b><small>${money(p.price)} ج</small></span><button class="btn" onclick='openProduct(${idArg(p.id)})'>عرض</button><button class="btn danger" onclick='toggleFav(${idArg(p.id)});openFavoritesModal()'>حذف</button></div>`).join('')}</div>`:'<div class="empty">مفيش منتجات محفوظة.</div>'}`;openModal('favoritesModal')}
function checkout(){if(!cart.length){toast('السلة فاضية');return}if(!currentUser){toast('سجّل الدخول لإتمام الطلب');openAccount();return}closeCart();renderCheckout();openModal('checkoutModal')}
async function renderCheckout(){const {data}=await sb.from('profiles').select('*').eq('id',currentUser.id).maybeSingle();const total=subtotal()*(coupon?.percent?1-coupon.percent/100:1);$('checkoutView').innerHTML=`<h2>إتمام الطلب</h2><div class="checkoutGrid"><div><h3>بيانات الشحن</h3><form id="checkoutForm"><input id="coName" required placeholder="الاسم" value="${esc(data?.full_name||'')}"><input id="coPhone" required placeholder="رقم الهاتف" value="${esc(data?.phone||'')}"><input id="coAddress" required placeholder="العنوان بالتفصيل" value="${esc(data?.address||'')}"><input id="coCity" required placeholder="المحافظة / المدينة" value="${esc(data?.city||'')}"><textarea id="coNote" placeholder="ملاحظات للطلب"></textarea><h3>طريقة الدفع</h3><label class="paymentOption"><input type="radio" name="payment" value="card" checked> 💳 بطاقة بنكية (Visa / Mastercard)</label><label class="paymentOption"><input type="radio" name="payment" value="cod"> 💵 الدفع عند الاستلام</label><button class="btn primary fullBtn">تأكيد الطلب</button></form></div><aside class="summary"><h3>ملخص الطلب</h3>${cart.map(p=>`<div><span>${esc(p.name)} × ${p.qty||1}</span><b>${money(p.price*(p.qty||1))} ج</b></div>`).join('')}<hr><div><b>الإجمالي</b><strong>${money(total)} ج</strong></div></aside></div>`;$('checkoutForm').onsubmit=createOrder}
async function createOrder(e){e.preventDefault();if(!sb||!currentUser)return;const payload={shipping_name:$('coName').value.trim(),shipping_phone:$('coPhone').value.trim(),shipping_address:$('coAddress').value.trim(),shipping_city:$('coCity').value.trim(),customer_note:$('coNote').value.trim(),payment_method:document.querySelector('input[name="payment"]:checked').value};const items=cart.map(p=>({product_id:Number(p.id),name:p.name,quantity:p.qty||1,unit_price:p.price}));const {data,error}=await sb.rpc('create_order_secure',{p_order:payload,p_items:items,p_coupon_code:coupon?.code||null});if(error){toast(error.message);return}const order=data?.[0];if(!order){toast('تعذر إنشاء الطلب');return}cart=[];coupon=null;saveLocal();updateCart();closeModal('checkoutModal');if(payload.payment_method==='card'){toast('تم إنشاء الطلب. سيتم فتح بوابة الدفع...');await startPayment(order)}else{toast('تم إنشاء الطلب بنجاح ✅');showTracking(order.tracking_number||order.order_number)}}
async function startPayment(order){if(!payCfg.edge_function_url){showTracking(order.tracking_number||order.order_number);toast('الدفع بالبطاقة يحتاج نشر وظيفة الدفع في Supabase');return}const token=await getAccessToken();const r=await fetch(payCfg.edge_function_url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({order_id:order.id})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.checkout_url){toast(j.error||'تعذر فتح بوابة الدفع');showTracking(order.tracking_number||order.order_number);return}location.href=j.checkout_url}
async function getAccessToken(){const {data}=await sb.auth.getSession();return data.session?.access_token||''}
async function applyCoupon(){const code=$('couponInput').value.trim().toUpperCase();if(!code||!sb)return;const {data,error}=await sb.from('coupons').select('*').eq('code',code).eq('active',true).maybeSingle();if(error||!data){toast('كود الخصم غير صحيح');return}if(data.expires_at&&new Date(data.expires_at)<new Date()){toast('الكوبون منتهي');return}coupon=data;updateCart();toast(`تم تطبيق خصم ${data.percent}%`)}
function statusText(s){return ({pending_payment:'في انتظار الدفع',paid:'تم الدفع',processing:'قيد التجهيز',shipped:'تم الشحن',out_for_delivery:'خرج للتوصيل',delivered:'تم التسليم',cancelled:'ملغي'})[s]||s||'جديد'}
function statusSteps(status){const steps=['pending_payment','paid','processing','shipped','out_for_delivery','delivered'],i=steps.indexOf(status);return steps.map((s,n)=>`<div class="timelineStep ${n<=i?'done':''} ${s===status?'current':''}"><span>${n+1}</span><b>${statusText(s)}</b></div>`).join('')}
async function trackOrder(e,modal=false){e.preventDefault();const q=modal?$('trackingInputModal').value.trim():$('trackingInput').value.trim();await showTracking(q,modal)}
async function showTracking(q,modal=false){if(!sb){toast('قاعدة البيانات غير متصلة');return}const safe=q.replace(/[^\w\-@.\u0600-\u06FF ]/g,'');const {data,error}=await sb.from('orders').select('id,order_number,total,status,tracking_number,shipping_city,created_at,estimated_delivery,shipping_events(event_time,status,note,location)').or(`order_number.eq.${safe},tracking_number.eq.${safe}`).maybeSingle();const box=$(modal?'trackingResultModal':'trackingResult');if(error||!data){box.innerHTML='<div class="empty">مش لاقيين الطلب. راجع رقم الطلب أو رقم التتبع.</div>';if(modal)openModal('trackModal');return}box.innerHTML=`<div class="trackingCard"><div class="trackingHead"><div><small>رقم الطلب</small><b>${esc(data.order_number)}</b></div><div><small>رقم التتبع</small><b>${esc(data.tracking_number||'لم يصدر بعد')}</b></div><div><small>الحالة</small><strong class="status ${esc(data.status)}">${statusText(data.status)}</strong></div></div><div class="timeline">${statusSteps(data.status)}</div><div class="events">${(data.shipping_events||[]).sort((a,b)=>new Date(b.event_time)-new Date(a.event_time)).map(ev=>`<div class="event"><b>${statusText(ev.status)}</b><span>${esc(ev.location||'')} ${ev.note?'• '+esc(ev.note):''}</span><small>${new Date(ev.event_time).toLocaleString('ar-EG')}</small></div>`).join('')}</div>${data.estimated_delivery?`<div class="eta">🚚 موعد التسليم المتوقع: <b>${new Date(data.estimated_delivery).toLocaleDateString('ar-EG')}</b></div>`:''}</div>`;if(modal)openModal('trackModal');else box.scrollIntoView({behavior:'smooth',block:'center'})}
function openTrack(){openModal('trackModal');setTimeout(()=>$('trackingInputModal')?.focus(),0)}
function subscribe(e){e.preventDefault();const email=$('email').value.trim();if(sb)sb.from('subscribers').upsert({email}).then(r=>toast(r.error?r.error.message:'تم تسجيل بريدك للعروض'));else toast('تم تسجيل بريدك محليًا');e.target.reset()}
// Admin
async function openAdmin(){if(!currentUser){toast('سجّل الدخول أولًا');openAccount();return}if(!isAdmin){toast('لوحة الإدارة مخصصة لصاحب المتجر');return}openModal('adminModal');adminTab('products')}
function adminTab(tab){document.querySelectorAll('.adminTabs .tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('adminProducts').hidden=tab!=='products';$('adminOrders').hidden=tab!=='orders';$('adminSite').hidden=tab!=='site';if(tab==='products')renderAdmin();if(tab==='orders')renderAdminOrders();if(tab==='site'){$('heroTitleAdmin').value=siteSettings.hero_title||'';$('heroTextAdmin').value=siteSettings.hero_text||'';$('heroImageAdmin').value=siteSettings.hero_image||''}}
function renderAdmin(){const box=$('adminProducts');box.innerHTML=`<div class="adminToolbar"><div><button class="btn primary" onclick="showProductForm()">➕ إضافة منتج جديد</button><button class="btn affiliateBtn" onclick="showProductForm()">🔗 أضف منتج من رابط أفليت</button></div><b>${products.length} منتج</b></div><div class="affiliateGuide"><b>طريقة إضافة منتج أفليت:</b> ضع رابط الأفليت + ارفع صورة المنتج + اكتب الاسم والوصف والسعر ثم احفظ. رابط الشراء يظل محفوظًا مع المنتج ويظهر للعميل.</div><div class="adminList">${products.map(p=>`<div class="adminRow"><div class="mini">${p.image?`<img src="${esc(p.image)}">`:'🛍️'}</div><div class="adminInfo"><b>${esc(p.name)}</b><span>${money(p.price)} ج • ${esc(p.source)} • ${p.url?'🔗 رابط أفليت موجود':'⚠️ بدون رابط أفليت'}</span></div><button class="btn" onclick='editProduct(${idArg(p.id)})'>تعديل</button><button class="btn danger" onclick='deleteProduct(${idArg(p.id)})'>حذف</button></div>`).join('')||'<div class="empty">مفيش منتجات. اضغط إضافة منتج.</div>'}</div><div id="productEditor"></div>`}
function showProductForm(p=null){$('productEditor').innerHTML=`<form id="productForm" class="editor"><h3>${p?'✏️ تعديل المنتج':'➕ إضافة منتج أفليت جديد'}</h3><div class="affiliateBox"><label>🔗 رابط الأفليت — رابط الشراء للعميل<input id="pUrl" type="url" required placeholder="https://..." value="${esc(p?.url||'')}"></label><small>بعد حفظ المنتج، زر «شراء من المتجر الأصلي» يفتح هذا الرابط.</small></div><div class="formGrid"><label>اسم المنتج<input id="pName" required value="${esc(p?.name||'')}" placeholder="مثال: سماعة بلوتوث"></label><label>السعر<input id="pPrice" type="number" min="0" required value="${p?.price??''}"></label><label>السعر قبل الخصم<input id="pOld" type="number" min="0" value="${p?.old??''}"></label><label>المخزون<input id="pStock" type="number" min="0" value="${p?.stock??999}"></label><label>القسم<input id="pCat" required value="${esc(p?.cat||'إلكترونيات')}"></label><label>المتجر الأصلي<input id="pSource" value="${esc(p?.source||'متجر خارجي')}"></label><label class="full">🖼️ رابط صورة المنتج<input id="pImage" type="url" placeholder="https://...jpg" value="${esc(p?.image||'')}"></label><label class="full">📤 أو ارفع صورة المنتج من الجهاز<input id="pImageFile" type="file" accept="image/png,image/jpeg,image/webp"></label><label class="full">📝 وصف المنتج<textarea id="pDesc" rows="6" placeholder="اكتب وصف المنتج ومميزاته...">${esc(p?.description||'')}</textarea></label></div><div id="imagePreview" class="imagePreview">${p?.image?`<img src="${esc(p.image)}">`:'معاينة الصورة ستظهر هنا'}</div><button class="btn primary">💾 حفظ المنتج</button><button type="button" class="btn" onclick="renderAdmin()">إلغاء</button></form>`;$('productForm').onsubmit=e=>saveProduct(e,p?.id);$('pImage').oninput=()=>previewImage($('pImage').value);$('pImageFile').onchange=()=>previewFile($('pImageFile').files[0])}
function previewImage(url){if(/^https?:\/\//i.test(url))$('imagePreview').innerHTML=`<img src="${esc(url)}" onerror="this.parentElement.textContent='الرابط لا يعرض صورة مباشرة'">`}
function previewFile(file){if(!file)return;const u=URL.createObjectURL(file);$('imagePreview').innerHTML=`<img src="${u}">`}
async function uploadImage(file,folder='products'){if(!sb||!currentUser||!isAdmin||!file)return '';if(!['image/png','image/jpeg','image/webp'].includes(file.type)){toast('اختار صورة PNG أو JPG أو WEBP');return ''}if(file.size>5*1024*1024){toast('حجم الصورة لازم يكون أقل من 5 ميجابايت');return ''}const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${folder}/${currentUser.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('product-images').upload(path,file,{upsert:false,contentType:file.type,cacheControl:'31536000'});if(error){toast('فشل رفع الصورة: '+error.message);return ''}return sb.storage.from('product-images').getPublicUrl(path).data.publicUrl}
async function saveProduct(e,id){e.preventDefault();if(!sb||!isAdmin){toast('لازم تكون مدير المتجر');return}let image=$('pImage').value.trim();const file=$('pImageFile')?.files?.[0];if(file){const uploaded=await uploadImage(file,'products');if(uploaded)image=uploaded;else if(!image)return}const url=$('pUrl').value.trim();if(!/^https?:\/\//i.test(url)){toast('حط رابط أفليت صحيح يبدأ بـ https://');return}const payload={name:$('pName').value.trim(),price:+$('pPrice').value,old_price:+$('pOld').value||+$('pPrice').value,stock:+$('pStock').value,category:$('pCat').value.trim(),store:$('pSource').value.trim(),affiliate_url:url,image_url:image,description:$('pDesc').value.trim()};const r=id?await sb.from('products').update(payload).eq('id',id).select().single():await sb.from('products').insert(payload).select().single();if(r.error){toast(r.error.message);return}toast(id?'تم تحديث المنتج':'تمت إضافة المنتج بنجاح ✅');await loadProducts()}
async function editProduct(id){showProductForm(products.find(p=>String(p.id)===String(id)))}
async function deleteProduct(id){if(!confirm('حذف المنتج؟'))return;const r=await sb.from('products').delete().eq('id',id);if(r.error)toast(r.error.message);else{toast('تم حذف المنتج');await loadProducts()}}
async function renderAdminOrders(){const {data,error}=await sb.from('orders').select('id,order_number,total,status,payment_status,payment_method,tracking_number,shipping_city,created_at').order('created_at',{ascending:false});if(error){toast(error.message);return}$('adminOrders').innerHTML=`<div class="adminList">${(data||[]).map(o=>`<div class="adminOrder"><div><b>${esc(o.order_number)}</b><small>${money(o.total)} ج • ${esc(o.shipping_city||'')}</small></div><select onchange='updateOrderStatus(${idArg(o.id)},this.value)'>${['pending_payment','paid','processing','shipped','out_for_delivery','delivered','cancelled'].map(s=>`<option value="${s}" ${s===o.status?'selected':''}>${statusText(s)}</option>`).join('')}</select><input placeholder="رقم التتبع" value="${esc(o.tracking_number||'')}" onchange='updateTracking(${idArg(o.id)},this.value)'><span class="status ${esc(o.status)}">${statusText(o.status)}</span></div>`).join('')||'<div class="empty">مفيش طلبات.</div>'}</div>`}
async function updateOrderStatus(id,status){const payload={status};if(status==='paid')payload.payment_status='paid';const r=await sb.from('orders').update(payload).eq('id',id);if(r.error)toast(r.error.message);else{await sb.from('shipping_events').insert({order_id:id,status,note:'تحديث من لوحة الإدارة'});toast('تم تحديث حالة الطلب')}}
async function updateTracking(id,tracking){const r=await sb.from('orders').update({tracking_number:tracking}).eq('id',id);if(r.error)toast(r.error.message);else toast('تم حفظ رقم التتبع')}
async function saveSiteSettings(){if(!sb||!isAdmin)return;let heroImage=$('heroImageAdmin').value.trim();const file=$('heroImageFile')?.files?.[0];if(file){const uploaded=await uploadImage(file,'site');if(uploaded)heroImage=uploaded;else if(!heroImage)return}const payload={hero_title:$('heroTitleAdmin').value,hero_text:$('heroTextAdmin').value,hero_image:heroImage};const r=siteSettings.id?await sb.from('site_settings').update(payload).eq('id',siteSettings.id):await sb.from('site_settings').insert(payload).select().single();if(r.error)toast(r.error.message);else{siteSettings={...siteSettings,...payload,...(r.data||{})};applySiteImage();toast('تم حفظ الواجهة')}}
function applySiteImage(){if(siteSettings.hero_image)document.querySelector('.hero').style.backgroundImage=`linear-gradient(90deg,#f8f6fbf2,#f8f6fbdd),url("${siteSettings.hero_image}")`}
init();
