-- فرتكه V2: الحسابات + الطلبات + الدفع + التتبع + المفضلة + الكوبونات + التقييمات
-- شغّل الملف كاملًا في Supabase SQL Editor.

create extension if not exists pgcrypto;

alter table public.profiles add column if not exists role text not null default 'customer';
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists address text;
alter table public.profiles add column if not exists city text;
alter table public.products add column if not exists old_price numeric(12,2);
alter table public.products add column if not exists stock integer not null default 999;
alter table public.products add column if not exists rating numeric(3,2) not null default 0;
alter table public.products add column if not exists review_count integer not null default 0;

create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  hero_title text,
  hero_text text,
  hero_image text,
  updated_at timestamptz not null default now()
);
insert into public.site_settings(hero_title,hero_text) select 'تسوق، ادفع، وتابع طلبك.','فرتكه بتجمع لك المنتجات والعروض في مكان واحد، ومع حسابك تقدر تحفظ المفضلة وتعمل طلب وتتابع الشحنة خطوة بخطوة.' where not exists (select 1 from public.site_settings);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique not null,
  tracking_number text unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  subtotal numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  status text not null default 'pending_payment',
  payment_status text not null default 'pending',
  payment_method text not null default 'card',
  payment_reference text,
  shipping_name text not null,
  shipping_phone text not null,
  shipping_address text not null,
  shipping_city text,
  customer_note text,
  estimated_delivery date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null check(quantity>0),
  unit_price numeric(12,2) not null check(unit_price>=0),
  created_at timestamptz not null default now()
);

create table if not exists public.shipping_events (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  status text not null,
  note text,
  location text,
  event_time timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,product_id)
);

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text unique not null,
  percent numeric(5,2) not null check(percent>0 and percent<=100),
  active boolean not null default true,
  expires_at timestamptz,
  max_uses integer,
  uses integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  rating integer not null check(rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  unique(product_id,user_id)
);

create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  provider text not null,
  provider_reference text,
  amount numeric(12,2) not null,
  status text not null default 'pending',
  raw_response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_user_idx on public.orders(user_id,created_at desc);
create index if not exists orders_tracking_idx on public.orders(tracking_number);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists shipping_events_order_idx on public.shipping_events(order_id,event_time desc);
create index if not exists products_category_idx on public.products(category);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.shipping_events enable row level security;
alter table public.favorites enable row level security;
alter table public.coupons enable row level security;
alter table public.reviews enable row level security;
alter table public.payment_transactions enable row level security;
alter table public.site_settings enable row level security;

-- تنظيف سياسات قديمة بأسماء الإصدار الثاني

drop policy if exists "customers read own orders" on public.orders;
drop policy if exists "customers read own order items" on public.order_items;
drop policy if exists "customers read own shipping events" on public.shipping_events;
drop policy if exists "customers manage own favorites" on public.favorites;
drop policy if exists "public read active coupons" on public.coupons;
drop policy if exists "customers read reviews" on public.reviews;
drop policy if exists "customers write reviews" on public.reviews;
drop policy if exists "public read site settings" on public.site_settings;
drop policy if exists "admin manage orders" on public.orders;
drop policy if exists "admin manage shipping" on public.shipping_events;
drop policy if exists "admin manage site settings" on public.site_settings;

create policy "customers read own orders" on public.orders for select to authenticated using (user_id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
create policy "admin manage orders" on public.orders for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
create policy "customers read own order items" on public.order_items for select to authenticated using (exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))));
create policy "customers read own shipping events" on public.shipping_events for select to authenticated using (exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))));
create policy "admin manage shipping" on public.shipping_events for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

create policy "customers manage own favorites" on public.favorites for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "public read active coupons" on public.coupons for select to anon,authenticated using (active=true and (expires_at is null or expires_at>now()));
create policy "customers read reviews" on public.reviews for select to anon,authenticated using (true);
create policy "customers write reviews" on public.reviews for insert to authenticated with check (user_id=auth.uid());
create policy "public read site settings" on public.site_settings for select to anon,authenticated using (true);
create policy "admin manage site settings" on public.site_settings for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- وظيفة آمنة لإنشاء الطلب مع عناصره. تمنع العميل من إنشاء طلب باسم مستخدم آخر.
drop function if exists public.create_order_with_items(jsonb,jsonb);
create or replace function public.create_order_with_items(p_order jsonb,p_items jsonb)
returns table(id uuid,order_number text,tracking_number text,total numeric,status text)
language plpgsql security definer set search_path=public
as $$
declare
  v_order_id uuid;
  v_order_number text;
  v_tracking text;
  v_item jsonb;
  v_user uuid:=auth.uid();
  v_total numeric:=coalesce((p_order->>'total')::numeric,0);
  v_subtotal numeric:=coalesce((p_order->>'subtotal')::numeric,0);
  v_discount numeric:=coalesce((p_order->>'discount')::numeric,0);
  v_product_id bigint;
  v_qty integer;
  v_price numeric;
  v_stock integer;
begin
  if v_user is null then raise exception 'يجب تسجيل الدخول أولًا'; end if;
  if coalesce(jsonb_array_length(p_items),0)=0 then raise exception 'السلة فارغة'; end if;
  v_order_number:='FRK-'||to_char(now(),'YYYYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,6));
  v_tracking:='FRKTRK-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10));
  insert into public.orders(order_number,tracking_number,user_id,subtotal,discount,total,status,payment_status,payment_method,shipping_name,shipping_phone,shipping_address,shipping_city,customer_note)
  values(v_order_number,v_tracking,v_user,v_subtotal,v_discount,v_total,coalesce(p_order->>'status','pending_payment'),'pending',coalesce(p_order->>'payment_method','card'),coalesce(p_order->>'shipping_name',''),coalesce(p_order->>'shipping_phone',''),coalesce(p_order->>'shipping_address',''),p_order->>'shipping_city',p_order->>'customer_note') returning orders.id into v_order_id;
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_product_id:=(v_item->>'product_id')::bigint; v_qty:=(v_item->>'quantity')::integer; v_price:=(v_item->>'unit_price')::numeric;
    select stock into v_stock from public.products where products.id=v_product_id for update;
    if not found then raise exception 'المنتج غير موجود'; end if;
    if v_stock < v_qty then raise exception 'المخزون غير كافٍ للمنتج %',(v_item->>'name'); end if;
    insert into public.order_items(order_id,product_id,product_name,quantity,unit_price) values(v_order_id,v_product_id,coalesce(v_item->>'name','منتج'),v_qty,v_price);
    update public.products set stock=stock-v_qty where products.id=v_product_id;
  end loop;
  insert into public.shipping_events(order_id,status,note) values(v_order_id,'pending_payment','تم إنشاء الطلب');
  return query select o.id,o.order_number,o.tracking_number,o.total,o.status from public.orders o where o.id=v_order_id;
end; $$;
revoke all on function public.create_order_with_items(jsonb,jsonb) from public;
grant execute on function public.create_order_with_items(jsonb,jsonb) to authenticated;

-- المدير الأول: بعد إنشاء حسابك، استبدل البريد ثم شغّل السطر التالي.
-- update public.profiles set role='admin' where id=(select id from auth.users where email='YOUR-EMAIL@example.com');

-- مثال كوبون تجريبي:
-- insert into public.coupons(code,percent,expires_at) values('WELCOME10',10,now()+interval '30 days') on conflict(code) do nothing;
